# Generated by Django 5.2.8 on 2025-11-11 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(
                        default=list, help_text="Lista ordenada de tipos de widgets a mostrar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la configuración"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Fecha de última actualización"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario dueño de esta configuración",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Dashboard",
                "verbose_name_plural": "Configuraciones de Dashboard",
                "db_table": "dashboard_configurations",
            },
        ),
    ]
