# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("seguridad", "Seguridad"),
                            ("notificaciones", "Notificaciones"),
                            ("integraciones", "Integraciones"),
                            ("llamadas", "Llamadas"),
                            ("tickets", "Tickets"),
                            ("reportes", "Reportes"),
                            ("sistema", "Sistema"),
                        ],
                        db_index=True,
                        help_text="Categoria de la configuracion",
                        max_length=50,
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        db_index=True,
                        help_text="Clave unica de la configuracion",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("valor", models.TextField(help_text="Valor actual de la configuracion")),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("float", "Float"),
                            ("json", "JSON"),
                            ("email", "Email"),
                            ("url", "URL"),
                        ],
                        help_text="Tipo de dato del valor",
                        max_length=20,
                    ),
                ),
                (
                    "valor_default",
                    models.TextField(help_text="Valor por defecto de la configuracion"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripcion de la configuracion"),
                ),
                (
                    "activa",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si la configuracion esta activa",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Fecha de ultima actualizacion"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha de creacion"),
                ),
            ],
            options={
                "verbose_name": "Configuracion",
                "verbose_name_plural": "Configuraciones",
                "db_table": "configuracion",
                "ordering": ["categoria", "clave"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionHistorial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "clave",
                    models.CharField(
                        db_index=True,
                        help_text="Clave de la configuracion (desnormalizado para historico)",
                        max_length=100,
                    ),
                ),
                ("valor_anterior", models.TextField(help_text="Valor antes del cambio")),
                ("valor_nuevo", models.TextField(help_text="Valor despues del cambio")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Fecha y hora del cambio"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Direccion IP desde donde se realizo el cambio",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent del navegador", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Configuracion",
                "verbose_name_plural": "Historial de Configuraciones",
                "db_table": "configuracion_historial",
                "ordering": ["-timestamp"],
            },
        ),
    ]
