# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizo la ultima modificacion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuraciones_actualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configuracionhistorial",
            name="configuracion",
            field=models.ForeignKey(
                help_text="Configuracion modificada",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="configuration.configuracion",
            ),
        ),
        migrations.AddField(
            model_name="configuracionhistorial",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizo el cambio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modificaciones_configuracion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="configuracion",
            index=models.Index(
                fields=["categoria", "activa"], name="configuraci_categor_0d08c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracion",
            index=models.Index(fields=["clave"], name="configuraci_clave_e714af_idx"),
        ),
        migrations.AddIndex(
            model_name="configuracionhistorial",
            index=models.Index(fields=["clave", "-timestamp"], name="configuraci_clave_2abccd_idx"),
        ),
        migrations.AddIndex(
            model_name="configuracionhistorial",
            index=models.Index(
                fields=["modificado_por", "-timestamp"], name="configuraci_modific_de25d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionhistorial",
            index=models.Index(fields=["-timestamp"], name="configuraci_timesta_6734b2_idx"),
        ),
    ]
