# Generated by Django 5.2.8 on 2025-11-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETLJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("job_name", models.CharField(help_text="Nombre del job", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "En ejecucion"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        help_text="Estado",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, help_text="Inicio", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="Fin", null=True)),
                (
                    "records_extracted",
                    models.IntegerField(default=0, help_text="Registros extraidos"),
                ),
                (
                    "records_transformed",
                    models.IntegerField(default=0, help_text="Registros transformados"),
                ),
                ("records_loaded", models.IntegerField(default=0, help_text="Registros cargados")),
                ("records_failed", models.IntegerField(default=0, help_text="Registros fallidos")),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Mensaje error", null=True),
                ),
                (
                    "error_details",
                    models.JSONField(blank=True, default=dict, help_text="Detalles del error"),
                ),
                (
                    "execution_time_seconds",
                    models.FloatField(
                        blank=True, help_text="Tiempo de ejecucion en segundos", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Metadata adicional"),
                ),
            ],
            options={
                "verbose_name": "ETL Job",
                "verbose_name_plural": "ETL Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="etl_etljob_status_be2a13_idx"
                    ),
                    models.Index(
                        fields=["job_name", "-created_at"], name="etl_etljob_job_nam_306414_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ETLValidationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("error_type", models.CharField(help_text="Tipo de error", max_length=100)),
                ("error_message", models.TextField(help_text="Mensaje de error")),
                ("record_data", models.JSONField(default=dict, help_text="Datos del registro")),
                (
                    "field_name",
                    models.CharField(
                        blank=True, help_text="Campo con error", max_length=100, null=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("critical", "Critico"),
                        ],
                        default="error",
                        help_text="Severidad",
                        max_length=20,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job relacionado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_errors",
                        to="etl.etljob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error de validacion ETL",
                "verbose_name_plural": "Errores de validacion ETL",
                "ordering": ["-created_at"],
            },
        ),
    ]
