---
# ===================================================================
# CI/CD LOCAL PIPELINE CONFIGURATION - IACT Project
# Pipeline unificado UI (React) + API (Django)
# ===================================================================
version: "1.0"

metadata:
  project: "IACT---project"
  description: "Pipeline CI/CD local ejecutable offline"
  maintained_by: "DevOps Team"
  documentation: "docs/devops/automatizacion/ci_cd/"

# ===================================================================
# PIPELINE CONFIGURATION
# ===================================================================
pipeline:
  name: "IACT Local CI"
  description: "Validacion completa UI + API antes de push"

  # Comportamiento pipeline
  fail_fast: true         # Detener en primer error de stage
  parallel: true          # Ejecutar stages independientes en paralelo
  timeout: 600            # 10 min timeout total pipeline

  # Deteccion cambios inteligente
  smart_detection:
    enabled: true
    strategy: git_diff    # Detectar que cambio: UI, API, o ambos
    base_branch: main

# ===================================================================
# STAGES DEL PIPELINE
# ===================================================================
stages:
  # ─────────────────────────────────────────────────────────────────
  # STAGE 1: LINT
  # Linting de codigo UI (ESLint) + API (Ruff)
  # ─────────────────────────────────────────────────────────────────
  - name: lint
    description: "Linting UI (ESLint) + API (Ruff) + Markdown"
    parallel: true        # Jobs en paralelo
    depends_on: []        # Sin dependencias

    jobs:
      # Lint UI (JavaScript/React)
      - name: lint_ui
        description: "ESLint en UI (React/JS)"
        working_dir: ui/
        command: "npm run lint"
        continue_on_error: false
        timeout: 60       # 1 min

        # Ejecucion condicional (solo si UI cambio)
        condition:
          type: files_changed
          pattern: 'ui/**/*.(js|jsx|ts|tsx)'

        # Artifacts
        artifacts: []

        # Metricas
        metrics:
          - name: lint_errors_count
            extract_from: stdout
            regex: '(\d+) error'

      # Lint API (Python/Django)
      - name: lint_api
        description: "Ruff en API (Django/Python)"
        working_dir: api/callcentersite/
        command: "ruff check ."
        continue_on_error: false
        timeout: 60

        condition:
          type: files_changed
          pattern: 'api/**/*.py'

        artifacts: []

        metrics:
          - name: ruff_errors_count
            extract_from: stdout
            regex: 'Found (\d+) error'

      # Lint Markdown (docs)
      - name: lint_markdown
        description: "Markdownlint en documentacion"
        working_dir: docs/
        command: "markdownlint **/*.md --config ../.markdownlint.json"
        continue_on_error: true  # Warnings no bloquean
        timeout: 30

        condition:
          type: files_changed
          pattern: 'docs/**/*.md'

  # ─────────────────────────────────────────────────────────────────
  # STAGE 2: TEST
  # Tests UI (Jest) + API (Pytest) con coverage
  # ─────────────────────────────────────────────────────────────────
  - name: test
    description: "Tests UI (Jest) + API (Pytest) con coverage"
    parallel: true
    depends_on:
      - lint              # Solo ejecutar si lint paso

    jobs:
      # Tests UI (Jest + React Testing Library)
      - name: test_ui
        description: "Jest tests UI con coverage"
        working_dir: ui/
        command: "npm run test:coverage"
        continue_on_error: false
        timeout: 120      # 2 min

        condition:
          type: files_changed
          pattern: 'ui/**/*.(js|jsx|ts|tsx)'

        # Coverage threshold
        coverage:
          enabled: true
          threshold: 80
          file: coverage/coverage-summary.json
          format: json
          extract_path: '$.total.lines.pct'

        # Artifacts
        artifacts:
          - path: coverage/
            name: ui-coverage
            retention: 7    # days

        # Metricas
        metrics:
          - name: ui_tests_passed
            extract_from: stdout
            regex: 'Tests:.*?(\d+) passed'
          - name: ui_tests_failed
            extract_from: stdout
            regex: 'Tests:.*?(\d+) failed'
          - name: ui_coverage_pct
            extract_from: file
            file: coverage/coverage-summary.json
            path: '$.total.lines.pct'

      # Tests API (Pytest + Coverage)
      - name: test_api
        description: "Pytest tests API con coverage"
        working_dir: api/callcentersite/
        command: "pytest --cov --cov-report=json --cov-report=term --tb=short"
        continue_on_error: false
        timeout: 180      # 3 min

        condition:
          type: files_changed
          pattern: 'api/**/*.py'

        # Coverage threshold
        coverage:
          enabled: true
          threshold: 80
          file: coverage.json
          format: json
          extract_path: '$.totals.percent_covered'

        # Artifacts
        artifacts:
          - path: coverage.json
            name: api-coverage
            retention: 7
          - path: .coverage
            name: api-coverage-db
            retention: 7

        # Metricas
        metrics:
          - name: api_tests_passed
            extract_from: stdout
            regex: '(\d+) passed'
          - name: api_tests_failed
            extract_from: stdout
            regex: '(\d+) failed'
          - name: api_coverage_pct
            extract_from: file
            file: coverage.json
            path: '$.totals.percent_covered'

  # ─────────────────────────────────────────────────────────────────
  # STAGE 3: BUILD
  # Build UI (Webpack) + API (collectstatic)
  # ─────────────────────────────────────────────────────────────────
  - name: build
    description: "Build UI (Webpack production) + API (collectstatic)"
    parallel: true
    depends_on:
      - test

    jobs:
      # Build UI (Webpack production)
      - name: build_ui
        description: "Webpack build production"
        working_dir: ui/
        command: "npm run build"
        continue_on_error: false
        timeout: 120

        condition:
          type: files_changed
          pattern: 'ui/**/*.(js|jsx|ts|tsx|css|html)'

        # Artifacts
        artifacts:
          - path: dist/
            name: ui-bundle
            retention: 7

        # Metricas
        metrics:
          - name: bundle_size_kb
            extract_from: stdout
            regex: 'main\..*?\.js.*?(\d+) KiB'

      # Build API (Django collectstatic + check --deploy)
      - name: build_api
        description: "Django collectstatic + deployment checks"
        working_dir: api/callcentersite/
        command: |
          python manage.py collectstatic --noinput --clear &&
          python manage.py check --deploy
        continue_on_error: false
        timeout: 60

        condition:
          type: files_changed
          pattern: 'api/**/*.(py|html|css|js)'

        # Artifacts
        artifacts:
          - path: staticfiles/
            name: api-static
            retention: 7

  # ─────────────────────────────────────────────────────────────────
  # STAGE 4: VALIDATE
  # Validaciones especificas IACT (security, DB, constitucion, docs)
  # ─────────────────────────────────────────────────────────────────
  - name: validate
    description: "Validaciones especificas IACT"
    parallel: false       # Secuencial (algunas validaciones pesadas)
    depends_on:
      - build

    jobs:
      # Validacion seguridad
      - name: validate_security
        description: "Validar configuracion seguridad"
        working_dir: .
        command: "./scripts/validate_security_config.sh"
        continue_on_error: false
        timeout: 60

        condition:
          type: files_changed
          pattern: 'api/**/settings/**/*.py'

      # Validacion database router
      - name: validate_database_router
        description: "Validar database routing PostgreSQL+MariaDB"
        working_dir: .
        command: "./scripts/validate_database_router.sh"
        continue_on_error: false
        timeout: 30

        condition:
          type: files_changed
          pattern: 'api/**/(models|db_router)\.py'

      # Validacion constitucion (NUEVO)
      - name: validate_constitucion
        description: "Validar conformidad con constitucion"
        working_dir: .
        command: "./scripts/constitucion.sh --mode=validate-all"
        continue_on_error: true   # Warnings permitidos
        timeout: 60

        # Artifacts
        artifacts:
          - path: .automation-logs/constitucion/validate-all-*.log
            name: constitucion-report
            retention: 30

      # Validacion estructura docs
      - name: validate_docs_structure
        description: "Validar estructura documentacion"
        working_dir: .
        command: "./scripts/validar_estructura_docs.sh"
        continue_on_error: true
        timeout: 30

        condition:
          type: files_changed
          pattern: 'docs/**/*.md'

      # Validacion restricciones criticas
      - name: validate_critical_restrictions
        description: "Validar restricciones criticas proyecto"
        working_dir: .
        command: "./scripts/validate_critical_restrictions.sh"
        continue_on_error: false
        timeout: 30

# ===================================================================
# REPORTING CONFIGURATION
# ===================================================================
reporting:
  # Formato output
  format: text            # text | json | html
  verbosity: normal       # quiet | normal | verbose

  # Colores (solo si terminal soporta)
  colors: auto            # auto | always | never

  # Guardado artifacts
  save_artifacts: true
  artifacts_dir: .ci-artifacts
  retention_days: 7

  # Resumen final
  summary:
    enabled: true
    sections:
      - stage_results     # Resultado cada stage
      - metrics           # Metricas agregadas
      - coverage          # Coverage UI + API
      - timing            # Duracion stages
      - artifacts         # Artifacts generados

# ===================================================================
# LOGGING CONFIGURATION
# ===================================================================
logging:
  enabled: true
  directory: .automation-logs/ci-local
  retention_days: 30
  format: text

  # Niveles log
  level: INFO             # DEBUG | INFO | WARNING | ERROR

  # Log por stage
  per_stage: true

  # Timestamps
  timestamps: true

# ===================================================================
# NOTIFICATIONS (OPCIONAL)
# ===================================================================
notifications:
  # Notificacion exito
  on_success:
    enabled: true
    message: "CI Local: All stages passed"
    sound: false

  # Notificacion fallo
  on_failure:
    enabled: true
    message: "CI Local: Failed at stage {stage_name}"
    sound: true

  # Notificacion warnings
  on_warning:
    enabled: true
    message: "CI Local: Completed with {warning_count} warnings"
    sound: false

# ===================================================================
# HOOKS (PRE/POST PIPELINE)
# ===================================================================
hooks:
  # Pre-pipeline: ejecutar antes de pipeline
  pre_pipeline:
    enabled: true
    jobs:
      - name: fetch_main
        description: "Actualizar referencia main"
        command: "git fetch origin main"
        continue_on_error: true
        timeout: 10

  # Post-pipeline: ejecutar despues de pipeline
  post_pipeline:
    enabled: true
    jobs:
      - name: update_dora_metrics
        description: "Actualizar metricas DORA"
        command: "./scripts/generate_dora_report.sh"
        continue_on_error: true
        timeout: 30
