# Generated by Django 5.2.8 on 2025-11-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_merge_dashboard_initials"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardConfiguration",
        ),
    ]
