# Generated by Django 5.2.8 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("call_id", models.CharField(max_length=100, unique=True)),
                ("client_id", models.CharField(max_length=100)),
                ("call_date", models.DateTimeField()),
                ("duration_seconds", models.IntegerField()),
                ("call_type", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=50)),
                ("center_id", models.IntegerField()),
                ("service_id", models.IntegerField()),
                ("agent_id", models.CharField(blank=True, max_length=100, null=True)),
                ("queue_time_seconds", models.IntegerField(default=0)),
                ("talk_time_seconds", models.IntegerField(default=0)),
                ("hold_time_seconds", models.IntegerField(default=0)),
                ("transfer_count", models.IntegerField(default=0)),
                ("satisfaction_score", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "analítica de llamada",
                "verbose_name_plural": "analíticas de llamadas",
                "ordering": ("-call_date",),
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("date", models.DateField()),
                ("center_id", models.IntegerField()),
                ("total_calls", models.IntegerField(default=0)),
                ("successful_calls", models.IntegerField(default=0)),
                ("failed_calls", models.IntegerField(default=0)),
                ("avg_duration", models.FloatField(default=0.0)),
                ("avg_queue_time", models.FloatField(default=0.0)),
                ("avg_talk_time", models.FloatField(default=0.0)),
                ("max_queue_time", models.IntegerField(default=0)),
                ("total_talk_time", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "métrica diaria",
                "verbose_name_plural": "métricas diarias",
                "ordering": ("-date",),
                "unique_together": {("date", "center_id")},
            },
        ),
    ]
