# Generated by Django 5.2.8 on 2025-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                blank=True, default=dict, help_text="Detalles adicionales del evento"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Tipo de evento (LOGIN_SUCCESS, USER_LOCKED, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="result",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
