# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Excepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("titulo", models.CharField(help_text="Título de la excepción", max_length=200)),
                ("justificacion", models.TextField(help_text="Justificación detallada")),
                ("tipo", models.CharField(help_text="Tipo de excepción", max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="solicitada",
                        help_text="Estado actual de la excepción",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Excepción",
                "verbose_name_plural": "Excepciones",
                "db_table": "excepciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
