# Generated by Django 5.2.8 on 2025-11-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excepciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excepcion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Excepción",
                "verbose_name_plural": "Excepciones",
            },
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que aprobó/rechazó la excepción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excepciones_aprobadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("solicitada", "Solicitada"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="solicitada",
                help_text="Estado actual de la excepción",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="justificacion",
            field=models.TextField(help_text="Justificación detallada"),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="solicitado_por",
            field=models.ForeignKey(
                help_text="Usuario que solicitó la excepción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excepciones_solicitadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="tipo",
            field=models.CharField(help_text="Tipo de excepción", max_length=100),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="titulo",
            field=models.CharField(help_text="Título de la excepción", max_length=200),
        ),
        migrations.AlterField(
            model_name="excepcion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
        ),
    ]
