# Generated by Django 5.2.8 on 2025-11-11 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capacidad",
            options={
                "ordering": ["nombre_completo"],
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
            },
        ),
        migrations.AlterModelOptions(
            name="funcion",
            options={
                "ordering": ["orden_menu", "nombre"],
                "verbose_name": "Funcion",
                "verbose_name_plural": "Funciones",
            },
        ),
        migrations.AlterModelOptions(
            name="funcioncapacidad",
            options={
                "verbose_name": "Funcion-Capacidad",
                "verbose_name_plural": "Funcion-Capacidades",
            },
        ),
        migrations.AlterModelOptions(
            name="grupocapacidad",
            options={"verbose_name": "Grupo-Capacidad", "verbose_name_plural": "Grupo-Capacidades"},
        ),
        migrations.AlterModelOptions(
            name="permisoexcepcional",
            options={
                "verbose_name": "Permiso Excepcional",
                "verbose_name_plural": "Permisos Excepcionales",
            },
        ),
        migrations.RenameIndex(
            model_name="auditoriapermiso",
            new_name="permissions_usuario_e89522_idx",
            old_name="perm_aud_usuario_idx",
        ),
        migrations.RenameIndex(
            model_name="auditoriapermiso",
            new_name="permissions_timesta_4255f4_idx",
            old_name="perm_aud_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditoriapermiso",
            new_name="permissions_accion__0cd91d_idx",
            old_name="perm_aud_accion_idx",
        ),
        migrations.RenameIndex(
            model_name="capacidad",
            new_name="permissions_accion_24f4cf_idx",
            old_name="perm_cap_accion_idx",
        ),
        migrations.RenameIndex(
            model_name="capacidad",
            new_name="permissions_recurso_abe8c2_idx",
            old_name="perm_cap_recurso_idx",
        ),
        migrations.RenameIndex(
            model_name="capacidad",
            new_name="permissions_nivel_s_ff7fae_idx",
            old_name="perm_cap_sensib_idx",
        ),
        migrations.RenameIndex(
            model_name="funcion",
            new_name="permissions_dominio_083540_idx",
            old_name="perm_func_dominio_idx",
        ),
        migrations.RenameIndex(
            model_name="funcion",
            new_name="permissions_activa_74df68_idx",
            old_name="perm_func_activa_idx",
        ),
        migrations.RenameIndex(
            model_name="funcion",
            new_name="permissions_categor_b8d2d9_idx",
            old_name="perm_func_categoria_idx",
        ),
        migrations.RenameIndex(
            model_name="permisoexcepcional",
            new_name="permissions_usuario_a3375e_idx",
            old_name="perm_exc_usr_activo_idx",
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="accion_realizada",
            field=models.CharField(help_text="acceso_concedido, acceso_denegado", max_length=100),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="capacidad",
            field=models.CharField(help_text="Capacidad que se intento usar", max_length=200),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="ip_address",
            field=models.CharField(
                blank=True, default="", help_text="IP del usuario", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Datos adicionales en formato JSON"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="recurso_accedido",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL o recurso especifico accedido",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Timestamp del acceso"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="user_agent",
            field=models.TextField(blank=True, default="", help_text="User agent del navegador"),
        ),
    ]
