# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP")),
                ("username", models.CharField(max_length=150, verbose_name="usuario")),
                ("success", models.BooleanField(verbose_name="éxito")),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="fecha"),
                ),
                ("user_agent", models.TextField(verbose_name="user agent")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="razón"),
                ),
            ],
            options={
                "verbose_name": "intento de inicio de sesión",
                "verbose_name_plural": "intentos de inicio de sesión",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="SecurityQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.TextField(verbose_name="pregunta")),
                ("answer_hash", models.CharField(max_length=255, verbose_name="respuesta cifrada")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pregunta de seguridad",
                "verbose_name_plural": "preguntas de seguridad",
            },
        ),
    ]
