# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reportes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reporteclientesunicos",
            unique_together={("fecha_inicio", "fecha_fin")},
        ),
        migrations.AlterUniqueTogether(
            name="reportellamadasdia",
            unique_together={("fecha", "hora")},
        ),
        migrations.AlterUniqueTogether(
            name="reportemenuproblemas",
            unique_together={("fecha", "menu_id")},
        ),
        migrations.AlterUniqueTogether(
            name="reportetransferencias",
            unique_together={("fecha", "centro_origen", "centro_destino")},
        ),
        migrations.AlterUniqueTogether(
            name="reportetrimestral",
            unique_together={("trimestre", "anio")},
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to="reportes.reporttemplate",
            ),
        ),
    ]
