# Generated by Django 5.2.8 on 2025-11-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dora_metrics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dorametric",
            new_name="dora_metric_phase_n_ea676d_idx",
            old_name="dora_metric_phase_n_idx",
        ),
        migrations.RenameIndex(
            model_name="dorametric",
            new_name="dora_metric_feature_350bec_idx",
            old_name="dora_metric_feature_idx",
        ),
        migrations.RenameIndex(
            model_name="dorametric",
            new_name="dora_metric_created_faea00_idx",
            old_name="dora_metric_created_idx",
        ),
    ]
