# Generated by Django 5.2.8 on 2025-11-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dora_metrics", "0003_aitelemetry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aitelemetry",
            new_name="ai_telemetr_agent_i_720cab_idx",
            old_name="ai_telemetr_agent_i_idx",
        ),
        migrations.RenameIndex(
            model_name="aitelemetry",
            new_name="ai_telemetr_task_ty_f52c0a_idx",
            old_name="ai_telemetr_task_ty_idx",
        ),
        migrations.RenameIndex(
            model_name="aitelemetry",
            new_name="ai_telemetr_created_78853d_idx",
            old_name="ai_telemetr_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aitelemetry",
            new_name="ai_telemetr_human_f_2ebb95_idx",
            old_name="ai_telemetr_human_f_idx",
        ),
    ]
