#!/bin/bash
set -e

# Create release packages (zip and tar.gz) for distribution
# Usage: ./create-release-packages.sh v1.2.3

VERSION="$1"
VERSION_NUMBER="${VERSION#v}"

if [ -z "$VERSION" ]; then
    echo "ERROR: Version argument required"
    echo "Usage: $0 v1.2.3"
    exit 1
fi

echo "Creating release packages for $VERSION..."

# Create dist directory
mkdir -p dist
rm -rf dist/*

# Define package name
PACKAGE_NAME="iact-docs-${VERSION_NUMBER}"
TEMP_DIR="dist/${PACKAGE_NAME}"

# Create temporary directory structure
mkdir -p "$TEMP_DIR"

echo "Collecting files for release package..."

# Copy documentation
if [ -d "docs" ]; then
    echo "  - Copying docs/"
    cp -r docs "$TEMP_DIR/"
fi

# Copy README and LICENSE if they exist
for file in README.md LICENSE LICENSE.txt; do
    if [ -f "$file" ]; then
        echo "  - Copying $file"
        cp "$file" "$TEMP_DIR/"
    fi
done

# Create VERSION file
echo "$VERSION_NUMBER" > "$TEMP_DIR/VERSION"
echo "  - Created VERSION file"

# Create release info file
cat > "$TEMP_DIR/RELEASE_INFO.txt" << EOF
IACT Documentation Package
Version: $VERSION
Release Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Repository: https://github.com/2-Coatl/IACT---project

This package contains the complete documentation for IACT project.

Contents:
- docs/          - Project documentation (MkDocs)
- VERSION        - Release version number
- RELEASE_INFO.txt - This file

For more information, visit:
https://2-coatl.github.io/IACT---project

---
Generated by automated release workflow
EOF

echo "  - Created RELEASE_INFO.txt"

# Create ZIP archive
echo "Creating ZIP archive..."
cd dist
zip -r "${PACKAGE_NAME}.zip" "${PACKAGE_NAME}" -q
echo "Created: dist/${PACKAGE_NAME}.zip"

# Create TAR.GZ archive
echo "Creating TAR.GZ archive..."
tar -czf "${PACKAGE_NAME}.tar.gz" "${PACKAGE_NAME}"
echo "Created: dist/${PACKAGE_NAME}.tar.gz"

# Cleanup temp directory
rm -rf "${PACKAGE_NAME}"

# Show package info
cd ..
echo ""
echo "Package Information:"
echo "-----------------------------------"
ls -lh dist/
echo "-----------------------------------"

# Calculate checksums
echo ""
echo "Checksums:"
cd dist
for file in *.zip *.tar.gz; do
    if [ -f "$file" ]; then
        SHA256=$(sha256sum "$file" | awk '{print $1}')
        echo "  $file"
        echo "    SHA256: $SHA256"
    fi
done
cd ..

# Create checksums file
cd dist
sha256sum *.zip *.tar.gz > "${PACKAGE_NAME}.sha256"
echo "Created: dist/${PACKAGE_NAME}.sha256"
cd ..

echo ""
echo "Release packages created successfully in dist/"
