# Generated by Django 5.2.8 on 2025-11-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("politicas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="politica",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Política",
                "verbose_name_plural": "Políticas",
            },
        ),
        migrations.AlterField(
            model_name="politica",
            name="contenido",
            field=models.TextField(help_text="Contenido completo de la política"),
        ),
        migrations.AlterField(
            model_name="politica",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó esta versión",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="politicas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="politica",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
        ),
        migrations.AlterField(
            model_name="politica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("publicada", "Publicada"),
                    ("archivada", "Archivada"),
                ],
                default="borrador",
                help_text="Estado actual de la política",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="politica",
            name="publicado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que publicó la política",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="politicas_publicadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="politica",
            name="titulo",
            field=models.CharField(help_text="Título de la política", max_length=200),
        ),
        migrations.AlterField(
            model_name="politica",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
        ),
        migrations.AlterField(
            model_name="politica",
            name="version",
            field=models.IntegerField(default=1, help_text="Número de versión"),
        ),
    ]
