# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vm.hostname = 'callcenter-analytics'

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network "private_network",
  ip: "10.0.2.10",
  virtualbox__intnet: true,
  type: "dhcp"

      
  config.vm.network 'forwarded_port', guest: 5432, host: 15432, auto_correct: true
  config.vm.network 'forwarded_port', guest: 3306, host: 13306, auto_correct: true

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
    vb.cpus = 2
    # Performance optimizations
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--vram", "12"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]

    # Network optimizations
    vb.customize ["modifyvm", :id, "--nic2", "intnet"]
    vb.customize ["modifyvm", :id, "--intnet2", "db_private_network"]
  end

  config.vm.synced_folder ".", "/vagrant", create: true
  config.vm.provision 'shell', path: 'bootstrap.sh'
end
