# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditoriaPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capacidad",
                    models.CharField(help_text="Capacidad que se intento usar", max_length=200),
                ),
                (
                    "accion_realizada",
                    models.CharField(help_text="acceso_concedido, acceso_denegado", max_length=100),
                ),
                (
                    "recurso_accedido",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL o recurso especifico accedido",
                        max_length=200,
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, default="", help_text="IP del usuario", max_length=50
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", help_text="User agent del navegador"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Datos adicionales en formato JSON"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Timestamp del acceso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Permiso",
                "verbose_name_plural": "Auditorias de Permisos",
                "db_table": "permissions_auditoria_permisos",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Capacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="sistema.dominio.recurso.accion", max_length=200, unique=True
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripcion de la capacidad"),
                ),
                (
                    "accion",
                    models.CharField(
                        help_text="ver, crear, editar, eliminar, aprobar, etc", max_length=50
                    ),
                ),
                (
                    "recurso",
                    models.CharField(
                        help_text="dashboards, usuarios, metricas, etc", max_length=100
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        help_text="vistas, administracion, operaciones, etc", max_length=100
                    ),
                ),
                (
                    "nivel_sensibilidad",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("normal", "Normal"),
                            ("alto", "Alto"),
                            ("critico", "Critico"),
                        ],
                        default="normal",
                        help_text="Nivel de sensibilidad de la accion",
                        max_length=20,
                    ),
                ),
                (
                    "requiere_auditoria",
                    models.BooleanField(
                        default=False, help_text="Si se debe auditar cada uso de esta capacidad"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, help_text="Si la capacidad esta activa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
                "db_table": "permissions_capacidades",
                "ordering": ["nombre_completo"],
            },
        ),
        migrations.CreateModel(
            name="Funcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre corto: 'dashboards', 'usuarios'", max_length=100
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre completo: 'sistema.vistas.dashboards'",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripcion de la funcion"),
                ),
                (
                    "dominio",
                    models.CharField(
                        help_text="Dominio: vistas, administracion, operaciones, etc",
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Categoria: visualizacion, gestion, analisis, etc",
                        max_length=50,
                    ),
                ),
                ("icono", models.CharField(blank=True, help_text="Icono para UI", max_length=50)),
                (
                    "orden_menu",
                    models.IntegerField(default=0, help_text="Orden en menu de navegacion"),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, help_text="Si la funcion esta activa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Funcion",
                "verbose_name_plural": "Funciones",
                "db_table": "permissions_funciones",
                "ordering": ["orden_menu", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="FuncionCapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "requerida",
                    models.BooleanField(
                        default=False, help_text="Si es capacidad obligatoria para la funcion"
                    ),
                ),
                (
                    "visible_en_ui",
                    models.BooleanField(
                        default=True, help_text="Si se muestra en interfaz de usuario"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Funcion-Capacidad",
                "verbose_name_plural": "Funcion-Capacidades",
                "db_table": "permissions_funcion_capacidades",
            },
        ),
        migrations.CreateModel(
            name="GrupoCapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grupo-Capacidad",
                "verbose_name_plural": "Grupo-Capacidades",
                "db_table": "permissions_grupo_capacidades",
            },
        ),
        migrations.CreateModel(
            name="GrupoPermisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico: 'atencion_cliente', 'gestion_equipos'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "nombre_display",
                    models.CharField(
                        help_text="Nombre para mostrar: 'Atencion al Cliente'", max_length=200
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Descripcion funcional del grupo"),
                ),
                (
                    "tipo_acceso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("operativo", "Operativo"),
                            ("gestion", "Gestion"),
                            ("analisis", "Analisis"),
                            ("estrategico", "Estrategico"),
                            ("tecnico", "Tecnico"),
                            ("finanzas", "Finanzas"),
                            ("calidad", "Calidad"),
                        ],
                        help_text="Tipo de acceso (NO jerarquico)",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True, help_text="Si el grupo esta activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grupo de Permisos",
                "verbose_name_plural": "Grupos de Permisos",
                "db_table": "permissions_grupos_permisos",
                "ordering": ["nombre_display"],
            },
        ),
        migrations.CreateModel(
            name="PermisoExcepcional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("conceder", "Conceder"), ("revocar", "Revocar")],
                        help_text="conceder o revocar",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, help_text="Fecha fin (NULL = permanente)", null=True
                    ),
                ),
                ("motivo", models.TextField(help_text="Justificacion del permiso excepcional")),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si el permiso excepcional esta activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permiso Excepcional",
                "verbose_name_plural": "Permisos Excepcionales",
                "db_table": "permissions_permisos_excepcionales",
            },
        ),
        migrations.CreateModel(
            name="UsuarioGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha de asignacion"
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de expiracion (NULL = permanente)", null=True
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Si la asignacion esta activa"),
                ),
            ],
            options={
                "verbose_name": "Usuario-Grupo",
                "verbose_name_plural": "Usuarios-Grupos",
                "db_table": "permissions_usuarios_grupos",
            },
        ),
    ]
