# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriapermiso",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditorias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="capacidad",
            index=models.Index(fields=["accion"], name="permissions_accion_24f4cf_idx"),
        ),
        migrations.AddIndex(
            model_name="capacidad",
            index=models.Index(fields=["recurso"], name="permissions_recurso_abe8c2_idx"),
        ),
        migrations.AddIndex(
            model_name="capacidad",
            index=models.Index(
                fields=["nivel_sensibilidad"], name="permissions_nivel_s_ff7fae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funcion",
            index=models.Index(fields=["dominio"], name="permissions_dominio_083540_idx"),
        ),
        migrations.AddIndex(
            model_name="funcion",
            index=models.Index(fields=["activa"], name="permissions_activa_74df68_idx"),
        ),
        migrations.AddIndex(
            model_name="funcion",
            index=models.Index(fields=["categoria"], name="permissions_categor_b8d2d9_idx"),
        ),
        migrations.AddField(
            model_name="funcioncapacidad",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funciones",
                to="permissions.capacidad",
            ),
        ),
        migrations.AddField(
            model_name="funcioncapacidad",
            name="funcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacidades",
                to="permissions.funcion",
            ),
        ),
        migrations.AddField(
            model_name="grupocapacidad",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="permissions.capacidad",
            ),
        ),
        migrations.AddField(
            model_name="grupocapacidad",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacidades",
                to="permissions.grupopermisos",
            ),
        ),
        migrations.AddField(
            model_name="permisoexcepcional",
            name="autorizado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisos_autorizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permisoexcepcional",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permisos_excepcionales",
                to="permissions.capacidad",
            ),
        ),
        migrations.AddField(
            model_name="permisoexcepcional",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permisos_excepcionales_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuariogrupo",
            name="asignado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_asignados_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuariogrupo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="permissions.grupopermisos",
            ),
        ),
        migrations.AddField(
            model_name="usuariogrupo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriapermiso",
            index=models.Index(fields=["usuario"], name="permissions_usuario_e89522_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoriapermiso",
            index=models.Index(fields=["timestamp"], name="permissions_timesta_4255f4_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoriapermiso",
            index=models.Index(fields=["accion_realizada"], name="permissions_accion__0cd91d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="funcioncapacidad",
            unique_together={("funcion", "capacidad")},
        ),
        migrations.AlterUniqueTogether(
            name="grupocapacidad",
            unique_together={("grupo", "capacidad")},
        ),
        migrations.AddIndex(
            model_name="permisoexcepcional",
            index=models.Index(fields=["usuario", "activo"], name="permissions_usuario_a3375e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usuariogrupo",
            unique_together={("usuario", "grupo")},
        ),
    ]
