# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.FileField(upload_to="reports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("file_size", models.BigIntegerField(default=0)),
                ("record_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "reporte generado",
                "verbose_name_plural": "reportes generados",
                "ordering": ("-generated_at",),
            },
        ),
        migrations.CreateModel(
            name="ReporteClientesUnicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("fecha_inicio", models.DateField(help_text="Fecha de inicio del período")),
                ("fecha_fin", models.DateField(help_text="Fecha de fin del período")),
                (
                    "total_clientes_unicos",
                    models.IntegerField(default=0, help_text="Total de clientes únicos"),
                ),
                (
                    "nuevos_clientes",
                    models.IntegerField(
                        default=0, help_text="Clientes que llamaron por primera vez"
                    ),
                ),
                (
                    "clientes_recurrentes",
                    models.IntegerField(
                        default=0, help_text="Clientes que ya habían llamado antes"
                    ),
                ),
                (
                    "promedio_llamadas_cliente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Promedio de llamadas por cliente",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de clientes únicos",
                "verbose_name_plural": "reportes de clientes únicos",
                "ordering": ("-fecha_inicio",),
            },
        ),
        migrations.CreateModel(
            name="ReporteLlamadasDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("fecha", models.DateField(help_text="Fecha del reporte")),
                ("hora", models.IntegerField(help_text="Hora del día (0-23)")),
                ("total_llamadas", models.IntegerField(default=0, help_text="Total de llamadas")),
                (
                    "llamadas_atendidas",
                    models.IntegerField(default=0, help_text="Llamadas atendidas"),
                ),
                (
                    "llamadas_abandonadas",
                    models.IntegerField(default=0, help_text="Llamadas abandonadas"),
                ),
                (
                    "tiempo_promedio_espera",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio de espera (segundos)",
                        max_digits=10,
                    ),
                ),
                (
                    "tiempo_promedio_atencion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio de atención (segundos)",
                        max_digits=10,
                    ),
                ),
                (
                    "nivel_servicio",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Nivel de servicio (%)", max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de llamadas por día",
                "verbose_name_plural": "reportes de llamadas por día",
                "ordering": ("-fecha", "hora"),
            },
        ),
        migrations.CreateModel(
            name="ReporteMenuProblemas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("fecha", models.DateField(help_text="Fecha del reporte")),
                ("menu_id", models.CharField(help_text="ID del menú IVR", max_length=50)),
                ("menu_nombre", models.CharField(help_text="Nombre del menú", max_length=200)),
                (
                    "veces_accedido",
                    models.IntegerField(default=0, help_text="Veces que se accedió al menú"),
                ),
                ("abandonos", models.IntegerField(default=0, help_text="Abandonos en el menú")),
                ("timeout", models.IntegerField(default=0, help_text="Timeout en el menú")),
                ("errores", models.IntegerField(default=0, help_text="Errores en el menú")),
                (
                    "tasa_abandono",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Tasa de abandono (%)", max_digits=5
                    ),
                ),
                (
                    "tiempo_promedio_permanencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio en el menú (segundos)",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de menú problemático",
                "verbose_name_plural": "reportes de menús problemáticos",
                "ordering": ("-fecha", "-abandonos"),
            },
        ),
        migrations.CreateModel(
            name="ReporteTransferencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("fecha", models.DateField(help_text="Fecha del reporte")),
                (
                    "centro_origen",
                    models.CharField(help_text="Centro de atención origen", max_length=100),
                ),
                (
                    "centro_destino",
                    models.CharField(help_text="Centro de atención destino", max_length=100),
                ),
                (
                    "total_transferencias",
                    models.IntegerField(default=0, help_text="Total de transferencias"),
                ),
                (
                    "transferencias_exitosas",
                    models.IntegerField(
                        default=0, help_text="Transferencias completadas exitosamente"
                    ),
                ),
                (
                    "transferencias_fallidas",
                    models.IntegerField(default=0, help_text="Transferencias fallidas"),
                ),
                (
                    "tiempo_promedio_transferencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio de transferencia en segundos",
                        max_digits=10,
                    ),
                ),
                (
                    "tasa_exito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tasa de éxito en porcentaje",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de transferencias",
                "verbose_name_plural": "reportes de transferencias",
                "ordering": ("-fecha", "centro_origen"),
            },
        ),
        migrations.CreateModel(
            name="ReporteTrimestral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("Q1", "Primer Trimestre"),
                            ("Q2", "Segundo Trimestre"),
                            ("Q3", "Tercer Trimestre"),
                            ("Q4", "Cuarto Trimestre"),
                        ],
                        help_text="Trimestre del reporte",
                        max_length=2,
                    ),
                ),
                ("anio", models.IntegerField(help_text="Anio del reporte")),
                (
                    "total_llamadas",
                    models.IntegerField(default=0, help_text="Total de llamadas en el trimestre"),
                ),
                (
                    "llamadas_atendidas",
                    models.IntegerField(default=0, help_text="Llamadas atendidas exitosamente"),
                ),
                (
                    "llamadas_abandonadas",
                    models.IntegerField(default=0, help_text="Llamadas abandonadas"),
                ),
                (
                    "tiempo_promedio_espera",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio de espera en segundos",
                        max_digits=10,
                    ),
                ),
                (
                    "tiempo_promedio_atencion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tiempo promedio de atención en segundos",
                        max_digits=10,
                    ),
                ),
                (
                    "nivel_servicio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nivel de servicio en porcentaje",
                        max_digits=5,
                    ),
                ),
                (
                    "tasa_abandono",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tasa de abandono en porcentaje",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte trimestral",
                "verbose_name_plural": "reportes trimestrales",
                "ordering": ("-anio", "-trimestre"),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("query_config", models.JSONField(default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("pdf", "PDF")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "plantilla de reporte",
                "verbose_name_plural": "plantillas de reporte",
                "ordering": ("name",),
            },
        ),
    ]
