# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo completo: sistema.administracion.usuarios.crear",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("requiere_aprobacion", models.BooleanField(default=False)),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("critico", "Critico"),
                        ],
                        default="bajo",
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
                "db_table": "capacidades",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Funcion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre corto: dashboards, usuarios", max_length=100
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre completo: sistema.vistas.dashboards",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        help_text="Dominio: vistas, administracion, operaciones", max_length=100
                    ),
                ),
                ("categoria", models.CharField(help_text="Categoria funcional", max_length=50)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("icono", models.CharField(blank=True, max_length=50, null=True)),
                ("orden_menu", models.IntegerField(default=999)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Funcion",
                "verbose_name_plural": "Funciones",
                "db_table": "funciones",
                "ordering": ["orden_menu", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Nombre de usuario único", max_length=150, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Email del usuario", max_length=255, unique=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Si el usuario está activo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        help_text="Estado del usuario",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, help_text="Si la cuenta está bloqueada"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp hasta cuando está bloqueada", null=True
                    ),
                ),
                (
                    "lock_reason",
                    models.CharField(
                        blank=True, default="", help_text="Razón del bloqueo", max_length=50
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, help_text="Contador de intentos fallidos de login"
                    ),
                ),
                (
                    "last_failed_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp del último intento fallido", null=True
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, default="", help_text="IP del último login", max_length=50
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp del último login exitoso", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Marca de borrado lógico"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp del borrado", null=True),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True, default="", help_text="Segmento del usuario", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp de última actualización"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Si el usuario puede acceder al admin"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaPermiso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("capacidad_codigo", models.CharField(max_length=200)),
                ("recurso_tipo", models.CharField(blank=True, default="", max_length=100)),
                ("recurso_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("acceso_permitido", "Acceso Permitido"),
                            ("acceso_denegado", "Acceso Denegado"),
                            ("asignacion_grupo", "Asignacion de Grupo"),
                            ("revocacion_grupo", "Revocacion de Grupo"),
                            ("permiso_excepcional", "Permiso Excepcional"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("exito", "Exito"),
                            ("fallo", "Fallo"),
                            ("permitido", "Permitido"),
                            ("denegado", "Denegado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("razon", models.TextField(blank=True, default="")),
                ("detalles", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("contexto_adicional", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Permiso",
                "verbose_name_plural": "Auditorias de Permisos",
                "db_table": "auditoria_permisos",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FuncionCapacidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "es_requerida",
                    models.BooleanField(
                        default=True, help_text="Si es requerida para acceder a la funcion"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capacidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_funciones",
                        to="users.capacidad",
                    ),
                ),
                (
                    "funcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funciones_capacidades",
                        to="users.funcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcion-Capacidad",
                "verbose_name_plural": "Funciones-Capacidades",
                "db_table": "funcion_capacidades",
            },
        ),
        migrations.AddField(
            model_name="funcion",
            name="capacidades",
            field=models.ManyToManyField(
                related_name="funciones", through="users.FuncionCapacidad", to="users.capacidad"
            ),
        ),
        migrations.CreateModel(
            name="GrupoCapacidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capacidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_grupos",
                        to="users.capacidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo-Capacidad",
                "verbose_name_plural": "Grupos-Capacidades",
                "db_table": "grupo_capacidades",
            },
        ),
        migrations.CreateModel(
            name="GrupoPermiso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo: administracion_usuarios, atencion_cliente",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.CharField(help_text="tecnico, operativo, gestion", max_length=50),
                ),
                ("requiere_aprobacion", models.BooleanField(default=False)),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("critico", "Critico"),
                        ],
                        default="bajo",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capacidades",
                    models.ManyToManyField(
                        related_name="grupos", through="users.GrupoCapacidad", to="users.capacidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Permisos",
                "verbose_name_plural": "Grupos de Permisos",
                "db_table": "grupos_permisos",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="grupocapacidad",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos_capacidades",
                to="users.grupopermiso",
            ),
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_password_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermisoExcepcional",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("temporal", "Temporal"), ("permanente", "Permanente")],
                        default="temporal",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(default=django.utils.timezone.now)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capacidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.capacidad"
                    ),
                ),
                (
                    "otorgado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permisos_otorgados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos_excepcionales_granular",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso Excepcional",
                "verbose_name_plural": "Permisos Excepcionales",
                "db_table": "permisos_excepcionales",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Clave única de sesión", max_length=255, unique=True
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Último timestamp de actividad en la sesión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Si la sesión está activa"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP de origen de la sesión", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="User agent del navegador/dispositivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp de creación de sesión"
                    ),
                ),
                (
                    "logged_out_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp de cierre de sesión", null=True
                    ),
                ),
                (
                    "logout_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Razón del cierre de sesión",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario dueño de la sesión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuario",
                "db_table": "users_user_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioGrupo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_asignacion", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "fecha_expiracion",
                    models.DateTimeField(blank=True, help_text="NULL = permanente", null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("motivo", models.TextField(blank=True, null=True)),
                (
                    "asignado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_usuarios",
                        to="users.grupopermiso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_grupos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Grupo",
                "verbose_name_plural": "Usuarios-Grupos",
                "db_table": "usuarios_grupos",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_user_usernam_65d164_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_user_is_acti_ddda02_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_deleted"], name="users_user_is_dele_968435_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoriapermiso",
            index=models.Index(fields=["usuario", "timestamp"], name="idx_auditoria_usuario_time"),
        ),
        migrations.AddIndex(
            model_name="auditoriapermiso",
            index=models.Index(
                fields=["capacidad_codigo", "timestamp"], name="idx_auditoria_cap_time"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="funcioncapacidad",
            unique_together={("funcion", "capacidad")},
        ),
        migrations.AlterUniqueTogether(
            name="grupocapacidad",
            unique_together={("grupo", "capacidad")},
        ),
        migrations.AddIndex(
            model_name="permisoexcepcional",
            index=models.Index(fields=["usuario", "activo"], name="idx_permiso_exc_usuario"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["user", "is_active"], name="users_user__user_id_1c146b_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["session_key"], name="users_user__session_c6bca5_idx"),
        ),
        migrations.AddIndex(
            model_name="usuariogrupo",
            index=models.Index(fields=["usuario", "activo"], name="idx_usuario_activo"),
        ),
        migrations.AlterUniqueTogether(
            name="usuariogrupo",
            unique_together={("usuario", "grupo")},
        ),
    ]
