# Generated by Django 5.2.8 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Nombre de usuario único", max_length=150, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Email del usuario", max_length=255, unique=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Si el usuario está activo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        help_text="Estado del usuario",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, help_text="Si la cuenta está bloqueada"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp hasta cuando está bloqueada", null=True
                    ),
                ),
                (
                    "lock_reason",
                    models.CharField(
                        blank=True, default="", help_text="Razón del bloqueo", max_length=50
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, help_text="Contador de intentos fallidos de login"
                    ),
                ),
                (
                    "last_failed_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp del último intento fallido", null=True
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, default="", help_text="IP del último login", max_length=50
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp del último login exitoso", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Marca de borrado lógico"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp del borrado", null=True),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True, default="", help_text="Segmento del usuario", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp de última actualización"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Si el usuario puede acceder al admin"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users_user",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["username"], name="users_user_usernam_65d164_idx"),
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["is_active"], name="users_user_is_acti_ddda02_idx"),
                    models.Index(fields=["is_deleted"], name="users_user_is_dele_968435_idx"),
                ],
            },
        ),
    ]
