# Generated by Django 5.2.8 on 2025-11-20 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_permisoexcepcional_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoriapermiso",
            name="detalles",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditoriapermiso",
            name="razon",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditoriapermiso",
            name="recurso_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auditoriapermiso",
            name="recurso_tipo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("exito", "Exito"),
                    ("fallo", "Fallo"),
                    ("permitido", "Permitido"),
                    ("denegado", "Denegado"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_password_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Clave única de sesión", max_length=255, unique=True
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Último timestamp de actividad en la sesión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Si la sesión está activa"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP de origen de la sesión", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="User agent del navegador/dispositivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp de creación de sesión"
                    ),
                ),
                (
                    "logged_out_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp de cierre de sesión", null=True
                    ),
                ),
                (
                    "logout_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Razón del cierre de sesión",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario dueño de la sesión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuario",
                "db_table": "users_user_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="users_user__user_id_1c146b_idx"
                    ),
                    models.Index(fields=["session_key"], name="users_user__session_c6bca5_idx"),
                ],
            },
        ),
    ]
