# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardConfiguracion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "configuracion",
                    models.JSONField(
                        default=dict, help_text="Configuracion de widgets y layout en formato JSON"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Fecha de ultima actualizacion"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha de creacion"),
                ),
            ],
            options={
                "verbose_name": "Configuracion de Dashboard",
                "verbose_name_plural": "Configuraciones de Dashboards",
                "db_table": "dashboard_configuracion",
                "ordering": ["-updated_at"],
            },
        ),
    ]
