#!/bin/bash
# generate_docs_stats.sh
# Generator: Documentation statistics and structure validation
#
# CONSTITUTION COMPLIANCE:
#   Rule 1: Single Responsibility - Only generates docs statistics
#   Rule 3: Explicit Error Handling - set -euo pipefail
#   Rule 5: Clean Code Naming - Descriptive function and variable names
#
# EXIT CODES:
#   0 - Statistics generated successfully
#   1 - Error generating statistics

set -euo pipefail

# Constants
readonly SCRIPT_NAME="$(basename "$0")"
readonly PROJECT_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
readonly DOCS_PATH="${PROJECT_ROOT}/docs"

# Colors for output
readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Logging functions
log_success() {
    echo -e "${GREEN}[OK]${NC} $*"
}

log_error() {
    echo -e "${RED}[X]${NC} $*"
}

log_header() {
    echo -e "${BLUE}$*${NC}"
}

# Main function
main() {
    if [ ! -d "$DOCS_PATH" ]; then
        log_error "docs/ directory not found: ${DOCS_PATH}"
        return 1
    fi

    log_header "Documentation Statistics"
    log_header "========================="
    echo ""

    # Count markdown files
    local total backend frontend infra auto_gen

    total=$(find "$DOCS_PATH" -name "*.md" -type f | wc -l)

    if [ -d "$DOCS_PATH/backend" ]; then
        backend=$(find "$DOCS_PATH/backend" -name "*.md" -type f 2>/dev/null | wc -l)
    else
        backend=0
    fi

    if [ -d "$DOCS_PATH/frontend" ]; then
        frontend=$(find "$DOCS_PATH/frontend" -name "*.md" -type f 2>/dev/null | wc -l)
    else
        frontend=0
    fi

    if [ -d "$DOCS_PATH/infrastructure" ]; then
        infra=$(find "$DOCS_PATH/infrastructure" -name "*.md" -type f 2>/dev/null | wc -l)
    else
        infra=0
    fi

    auto_gen=$(grep -r "auto_generado: true" "$DOCS_PATH" --include="*.md" -l 2>/dev/null | wc -l || echo 0)

    echo "Total .md files: $total"
    echo "  - Backend: $backend"
    echo "  - Frontend: $frontend"
    echo "  - Infrastructure: $infra"
    echo "  - Auto-generated: $auto_gen"

    echo ""
    log_header "Structure validation:"
    echo ""

    # Check expected directories
    if [ -d "$DOCS_PATH/backend" ]; then
        log_success "docs/backend/ exists"
    else
        log_error "docs/backend/ missing"
    fi

    if [ -d "$DOCS_PATH/frontend" ]; then
        log_success "docs/frontend/ exists"
    else
        log_error "docs/frontend/ missing"
    fi

    if [ -d "$DOCS_PATH/infrastructure" ]; then
        log_success "docs/infrastructure/ exists"
    else
        log_error "docs/infrastructure/ missing"
    fi

    # Check for old structure
    if [ -d "$DOCS_PATH/implementacion" ]; then
        log_error "docs/implementacion/ still exists (should be removed)"
    else
        log_success "docs/implementacion/ properly removed"
    fi

    echo ""

    # Output for GitHub Actions
    if [ -n "${GITHUB_OUTPUT:-}" ]; then
        echo "total_docs=$total" >> "$GITHUB_OUTPUT"
        echo "backend_docs=$backend" >> "$GITHUB_OUTPUT"
        echo "frontend_docs=$frontend" >> "$GITHUB_OUTPUT"
        echo "infrastructure_docs=$infra" >> "$GITHUB_OUTPUT"
        echo "autogenerated_docs=$auto_gen" >> "$GITHUB_OUTPUT"
    fi

    return 0
}

main "$@"
