#!/bin/bash
# validate_autogenerated_docs.sh
# Validator: Check auto-generated documentation metadata
#
# CONSTITUTION COMPLIANCE:
#   Rule 1: Single Responsibility - Only validates auto-generated docs metadata
#   Rule 3: Explicit Error Handling - set -euo pipefail
#   Rule 5: Clean Code Naming - Descriptive function and variable names
#
# EXIT CODES:
#   0 - All auto-generated docs have proper metadata
#   1 - Missing required metadata fields

set -euo pipefail

# Constants
readonly SCRIPT_NAME="$(basename "$0")"
readonly PROJECT_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
readonly DOCS_PATH="${PROJECT_ROOT}/docs"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly NC='\033[0m' # No Color

# Required metadata fields for auto-generated docs
readonly REQUIRED_FIELDS=("id" "tipo" "dominio" "fecha")

# Logging functions
log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $*"
}

log_info() {
    echo "[INFO] $*"
}

# Validate single auto-generated document
validate_document() {
    local doc="$1"
    local errors=0

    log_info "Checking: $doc"

    # Check for each required metadata field
    for field in "${REQUIRED_FIELDS[@]}"; do
        if ! grep -q "^${field}: " "$doc"; then
            log_error "Missing '${field}' field in $doc"
            errors=$((errors + 1))
        fi
    done

    return "$errors"
}

# Main function
main() {
    log_info "Validating auto-generated documentation metadata..."

    if [ ! -d "$DOCS_PATH" ]; then
        log_error "docs/ directory not found: ${DOCS_PATH}"
        return 1
    fi

    local error_count=0
    local docs_count=0

    # Find all docs marked as auto-generated
    while IFS= read -r doc; do
        if grep -q "auto_generado: true" "$doc"; then
            docs_count=$((docs_count + 1))
            validate_document "$doc" || error_count=$((error_count + $?))
        fi
    done < <(find "$DOCS_PATH" -name "*.md" -type f)

    echo ""
    log_info "Checked $docs_count auto-generated document(s)"

    if [ "$error_count" -gt 0 ]; then
        log_error "Found $error_count validation error(s) in auto-generated docs"
        echo ""
        echo "Required metadata fields for auto-generated docs:"
        for field in "${REQUIRED_FIELDS[@]}"; do
            echo "  - $field"
        done
        return 1
    else
        log_success "All auto-generated docs have proper metadata"
        return 0
    fi
}

main "$@"
