# Generated by Django 5.2.8 on 2025-11-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_configuracion_historial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="configuracion",
            new_name="configuraci_categor_0d08c5_idx",
            old_name="config_cat_act_idx",
        ),
        migrations.RenameIndex(
            model_name="configuracion",
            new_name="configuraci_clave_e714af_idx",
            old_name="config_clave_idx",
        ),
        migrations.RenameIndex(
            model_name="configuracionhistorial",
            new_name="configuraci_clave_2abccd_idx",
            old_name="config_hist_clave_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="configuracionhistorial",
            new_name="configuraci_modific_de25d0_idx",
            old_name="config_hist_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="configuracionhistorial",
            new_name="configuraci_timesta_6734b2_idx",
            old_name="config_hist_ts_idx",
        ),
        migrations.AlterField(
            model_name="configuracion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizo la ultima modificacion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuraciones_actualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
