# Generated by Django 5.2.8 on 2025-11-11 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstadoLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Codigo unico del estado", max_length=50, unique=True
                    ),
                ),
                ("nombre", models.CharField(help_text="Nombre del estado", max_length=100)),
                ("descripcion", models.TextField(blank=True, help_text="Descripcion del estado")),
                ("es_final", models.BooleanField(default=False, help_text="Si es un estado final")),
                ("activo", models.BooleanField(default=True, help_text="Si esta activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Estado de Llamada",
                "verbose_name_plural": "Estados de Llamadas",
                "db_table": "llamadas_estados",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Llamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        editable=False,
                        help_text="Codigo unico generado",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("numero_telefono", models.CharField(help_text="Numero telefonico", max_length=20)),
                ("cliente_nombre", models.CharField(blank=True, max_length=200, null=True)),
                ("cliente_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "cliente_id",
                    models.IntegerField(
                        blank=True, help_text="ID del cliente si existe", null=True
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Datos adicionales JSON"),
                ),
                ("notas", models.TextField(blank=True, help_text="Notas de la llamada")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Llamada",
                "verbose_name_plural": "Llamadas",
                "db_table": "llamadas",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="LlamadaGrabacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "archivo_url",
                    models.URLField(help_text="URL del archivo de grabacion", max_length=500),
                ),
                (
                    "formato",
                    models.CharField(help_text="Formato del audio (mp3, wav, etc)", max_length=10),
                ),
                ("duracion_segundos", models.IntegerField(help_text="Duracion en segundos")),
                (
                    "tamano_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Tamano del archivo en bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grabacion de Llamada",
                "verbose_name_plural": "Grabaciones de Llamadas",
                "db_table": "llamadas_grabaciones",
            },
        ),
        migrations.CreateModel(
            name="LlamadaTranscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("texto", models.TextField(help_text="Texto transcrito")),
                (
                    "timestamp_inicio",
                    models.IntegerField(help_text="Segundo de inicio en la grabacion"),
                ),
                ("timestamp_fin", models.IntegerField(help_text="Segundo de fin en la grabacion")),
                (
                    "hablante",
                    models.CharField(
                        help_text="Identificador del hablante (agente/cliente)", max_length=50
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        blank=True, help_text="Nivel de confianza de la transcripcion", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transcripcion de Llamada",
                "verbose_name_plural": "Transcripciones de Llamadas",
                "db_table": "llamadas_transcripciones",
                "ordering": ["llamada", "timestamp_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(help_text="Codigo unico del tipo", max_length=50, unique=True),
                ),
                ("nombre", models.CharField(help_text="Nombre del tipo", max_length=100)),
                ("descripcion", models.TextField(blank=True, help_text="Descripcion del tipo")),
                ("activo", models.BooleanField(default=True, help_text="Si esta activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Llamada",
                "verbose_name_plural": "Tipos de Llamadas",
                "db_table": "llamadas_tipos",
                "ordering": ["nombre"],
            },
        ),
    ]
