# Generated by Django 5.2.8 on 2025-11-11 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llamadas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llamada",
            name="agente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="llamadas_atendidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="llamadas",
                to="llamadas.estadollamada",
            ),
        ),
        migrations.AddField(
            model_name="llamadagrabacion",
            name="llamada",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grabacion",
                to="llamadas.llamada",
            ),
        ),
        migrations.AddField(
            model_name="llamadatranscripcion",
            name="llamada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripciones",
                to="llamadas.llamada",
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="llamadas",
                to="llamadas.tipollamada",
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(fields=["numero_telefono"], name="llamadas_numero__16635c_idx"),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["agente", "fecha_inicio"], name="llamadas_agente__8a8fbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(fields=["estado"], name="llamadas_estado__df82fa_idx"),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(fields=["fecha_inicio"], name="llamadas_fecha_i_24aa83_idx"),
        ),
    ]
