# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(blank=True, default="", max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tipo de evento (LOGIN_SUCCESS, USER_LOCKED, etc.)",
                        max_length=100,
                    ),
                ),
                ("resource", models.CharField(blank=True, default="", max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("result", models.CharField(blank=True, default="", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detalles adicionales del evento"
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ("-timestamp",),
                "permissions": [("view_auditlog", "Puede ver los registros de auditoría")],
                "default_permissions": (),
            },
        ),
    ]
