# Generated by Django 5.2.8 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.FileField(upload_to="reports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("file_size", models.BigIntegerField(default=0)),
                ("record_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "reporte generado",
                "verbose_name_plural": "reportes generados",
                "ordering": ("-generated_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("query_config", models.JSONField(default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("pdf", "PDF")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "plantilla de reporte",
                "verbose_name_plural": "plantillas de reporte",
                "ordering": ("name",),
            },
        ),
    ]
