# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("titulo", models.CharField(help_text="Título del presupuesto", max_length=200)),
                ("descripcion", models.TextField(help_text="Descripción detallada")),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, help_text="Monto total", max_digits=12),
                ),
                ("periodo_inicio", models.DateField(help_text="Fecha de inicio del período")),
                ("periodo_fin", models.DateField(help_text="Fecha de fin del período")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pendiente", "Pendiente Aprobación"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="borrador",
                        help_text="Estado actual del presupuesto",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "db_table": "presupuestos",
                "ordering": ["-created_at"],
            },
        ),
    ]
