# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("presupuestos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que aprobó/rechazó el presupuesto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presupuestos_aprobados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó el presupuesto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presupuestos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
