# Generated by Django 5.2.8 on 2025-11-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presupuesto",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que aprobó/rechazó el presupuesto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presupuestos_aprobados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó el presupuesto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presupuestos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="descripcion",
            field=models.TextField(help_text="Descripción detallada"),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("pendiente", "Pendiente Aprobación"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="borrador",
                help_text="Estado actual del presupuesto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="monto",
            field=models.DecimalField(decimal_places=2, help_text="Monto total", max_digits=12),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="periodo_fin",
            field=models.DateField(help_text="Fecha de fin del período"),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="periodo_inicio",
            field=models.DateField(help_text="Fecha de inicio del período"),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="titulo",
            field=models.CharField(help_text="Título del presupuesto", max_length=200),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
        ),
    ]
