# Generated by Django 5.2.8 on 2026-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Politica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de actualización"),
                ),
                ("titulo", models.CharField(help_text="Título de la política", max_length=200)),
                ("contenido", models.TextField(help_text="Contenido completo de la política")),
                ("version", models.IntegerField(default=1, help_text="Número de versión")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("archivada", "Archivada"),
                        ],
                        default="borrador",
                        help_text="Estado actual de la política",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Política",
                "verbose_name_plural": "Políticas",
                "db_table": "politicas",
                "ordering": ["-created_at"],
            },
        ),
    ]
