# Generated by Django 5.2.8 on 2026-01-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("politicas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="politica",
            name="creado_por",
            field=models.ForeignKey(
                help_text="Usuario que creó esta versión",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="politicas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="politica",
            name="publicado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que publicó la política",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="politicas_publicadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
