# Generated by Django 5.2.8 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="asunto")),
                ("body", models.TextField(verbose_name="cuerpo")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("alert", "Alerta"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="prioridad",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="leído")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fecha lectura"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "mensaje interno",
                "verbose_name_plural": "mensajes internos",
                "ordering": ("-created_at",),
            },
        ),
    ]
