# Generated by Django 5.2.8 on 2025-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmessage",
            name="created_by_system",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el mensaje fue generado automáticamente por el sistema",
                verbose_name="creado por sistema",
            ),
        ),
    ]
