# Generated by Django 5.2.8 on 2025-11-11 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0002_alter_capacidad_options_alter_funcion_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditoriapermiso",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditorias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="accion",
            field=models.CharField(
                help_text="ver, crear, editar, eliminar, aprobar, etc", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="activa",
            field=models.BooleanField(default=True, help_text="Si la capacidad esta activa"),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="dominio",
            field=models.CharField(
                help_text="vistas, administracion, operaciones, etc", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="nivel_sensibilidad",
            field=models.CharField(
                choices=[
                    ("bajo", "Bajo"),
                    ("normal", "Normal"),
                    ("alto", "Alto"),
                    ("critico", "Critico"),
                ],
                default="normal",
                help_text="Nivel de sensibilidad de la accion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="nombre_completo",
            field=models.CharField(
                help_text="sistema.dominio.recurso.accion", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="recurso",
            field=models.CharField(help_text="dashboards, usuarios, metricas, etc", max_length=100),
        ),
        migrations.AlterField(
            model_name="capacidad",
            name="requiere_auditoria",
            field=models.BooleanField(
                default=False, help_text="Si se debe auditar cada uso de esta capacidad"
            ),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="activa",
            field=models.BooleanField(default=True, help_text="Si la funcion esta activa"),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="categoria",
            field=models.CharField(
                blank=True,
                help_text="Categoria: visualizacion, gestion, analisis, etc",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="descripcion",
            field=models.TextField(blank=True, help_text="Descripcion de la funcion"),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="dominio",
            field=models.CharField(
                help_text="Dominio: vistas, administracion, operaciones, etc", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="nombre",
            field=models.CharField(
                help_text="Nombre corto: 'dashboards', 'usuarios'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="nombre_completo",
            field=models.CharField(
                help_text="Nombre completo: 'sistema.vistas.dashboards'",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="funcion",
            name="orden_menu",
            field=models.IntegerField(default=0, help_text="Orden en menu de navegacion"),
        ),
        migrations.AlterField(
            model_name="funcioncapacidad",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funciones",
                to="permissions.capacidad",
            ),
        ),
        migrations.AlterField(
            model_name="funcioncapacidad",
            name="funcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacidades",
                to="permissions.funcion",
            ),
        ),
        migrations.AlterField(
            model_name="funcioncapacidad",
            name="requerida",
            field=models.BooleanField(
                default=False, help_text="Si es capacidad obligatoria para la funcion"
            ),
        ),
        migrations.AlterField(
            model_name="funcioncapacidad",
            name="visible_en_ui",
            field=models.BooleanField(
                default=True, help_text="Si se muestra en interfaz de usuario"
            ),
        ),
        migrations.AlterField(
            model_name="grupocapacidad",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="permissions.capacidad",
            ),
        ),
        migrations.AlterField(
            model_name="grupocapacidad",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacidades",
                to="permissions.grupopermisos",
            ),
        ),
        migrations.AlterField(
            model_name="grupopermisos",
            name="activo",
            field=models.BooleanField(default=True, help_text="Si el grupo esta activo"),
        ),
        migrations.AlterField(
            model_name="grupopermisos",
            name="codigo",
            field=models.CharField(
                help_text="Codigo unico: 'atencion_cliente', 'gestion_equipos'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="grupopermisos",
            name="descripcion",
            field=models.TextField(blank=True, help_text="Descripcion funcional del grupo"),
        ),
        migrations.AlterField(
            model_name="grupopermisos",
            name="nombre_display",
            field=models.CharField(
                help_text="Nombre para mostrar: 'Atencion al Cliente'", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="grupopermisos",
            name="tipo_acceso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("operativo", "Operativo"),
                    ("gestion", "Gestion"),
                    ("analisis", "Analisis"),
                    ("estrategico", "Estrategico"),
                    ("tecnico", "Tecnico"),
                    ("finanzas", "Finanzas"),
                    ("calidad", "Calidad"),
                ],
                help_text="Tipo de acceso (NO jerarquico)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="activo",
            field=models.BooleanField(
                default=True, help_text="Si el permiso excepcional esta activo"
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="autorizado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisos_autorizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="capacidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permisos_excepcionales",
                to="permissions.capacidad",
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="fecha_fin",
            field=models.DateTimeField(
                blank=True, help_text="Fecha fin (NULL = permanente)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="fecha_inicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="motivo",
            field=models.TextField(help_text="Justificacion del permiso excepcional"),
        ),
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="tipo",
            field=models.CharField(
                choices=[("conceder", "Conceder"), ("revocar", "Revocar")],
                help_text="conceder o revocar",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="activo",
            field=models.BooleanField(default=True, help_text="Si la asignacion esta activa"),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="asignado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_asignados_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="fecha_asignacion",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Fecha de asignacion"
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="fecha_expiracion",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de expiracion (NULL = permanente)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="permissions.grupopermisos",
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
