# Generated by Django 5.2.8 on 2025-11-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_alter_auditoriapermiso_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="permisoexcepcional",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permisos_excepcionales_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
