# Generated by Django 5.2.8 on 2025-11-11 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Clave única de la configuración (ej: max_intentos_login)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("valor", models.TextField(help_text="Valor de la configuración")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("string", "Cadena de texto"),
                            ("integer", "Número entero"),
                            ("float", "Número decimal"),
                            ("boolean", "Booleano"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Tipo de dato del valor",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción de qué hace este parámetro"
                    ),
                ),
                ("valor_default", models.TextField(help_text="Valor por defecto si se resetea")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Fecha de última modificación"),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que modificó este parámetro",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuraciones_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "db_table": "configuracion_sistema",
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valor_anterior", models.TextField(help_text="Valor antes del cambio")),
                ("valor_nuevo", models.TextField(help_text="Valor después del cambio")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Cuándo se realizó el cambio"
                    ),
                ),
                ("motivo", models.TextField(blank=True, help_text="Razón del cambio (opcional)")),
                (
                    "modificado_por",
                    models.ForeignKey(
                        help_text="Usuario que realizó el cambio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_configuracion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuracion",
                    models.ForeignKey(
                        help_text="Configuración que fue modificada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="configuracion.configuracionsistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Configuración",
                "verbose_name_plural": "Auditorías de Configuración",
                "db_table": "auditoria_configuracion",
                "ordering": ["-timestamp"],
            },
        ),
    ]
