# Generated by Django 5.2.8 on 2025-11-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionsistema",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que modificó este parámetro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuracion_sistema_modificaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
